trigger:
  branches:
    include:
      - master
  paths:
    include:
      - api/**

pool:
  vmImage: ubuntu-latest

variables:
  working_dir: '$(System.DefaultWorkingDirectory)/api'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (f275f355-8e02-4494-bc67-197191969e80)'
    command: 'build'
    projects: '$(working_dir)/api.csproj'
    arguments: '--configuration Release --runtime linux-x64'

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (f275f355-8e02-4494-bc67-197191969e80)'
    command: 'publish'
    publishWebProjects: false
    projects: '$(working_dir)/api.csproj'
    arguments: '--configuration Release --runtime linux-x64'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (f275f355-8e02-4494-bc67-197191969e80)'
    appType: 'webAppLinux'
    WebAppName: 'spiritual-guide-api'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|9.0'
    StartupCommand: 'dotnet api.dll'
    AppSettings: |
      KEY_VAULT_URI=https://spiritkeys.vault.azure.net/
      AzureAd__Instance=https://login.microsoftonline.com/
      AzureAd__Domain=leobrowaldhgmail.onmicrosoft.com
      AzureAd__TenantId=b7fcc710-7abe-44d7-b015-60d1408db52e
      AzureAd__ClientId=d678e3ba-e30b-4721-8c5b-08ef71784074
      AzureAd__CallbackPath=/signin-oidc
      AzureAd__Scopes=access_as_user
      AzureWebJobsStorage__tableServiceUri=https://spiritualguide8313.table.core.windows.net

    DeploymentTypeLinux: 'zipDeploy'

