trigger:
  branches:
    include:
      - master
  paths:
    include:
      - api/**

pool:
  vmImage: ubuntu-latest

variables:
  working_dir: '$(System.DefaultWorkingDirectory)/api'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (f275f355-8e02-4494-bc67-197191969e80)'
    command: 'build'
    projects: '$(working_dir)/api.csproj'
    arguments: '--configuration Release --runtime linux-x64'

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (f275f355-8e02-4494-bc67-197191969e80)'
    command: 'publish'
    publishWebProjects: false
    projects: '$(working_dir)/api.csproj'
    arguments: '--configuration Release --runtime linux-x64'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (f275f355-8e02-4494-bc67-197191969e80)'
    appType: 'webAppLinux'
    WebAppName: 'spiritual-guide-api2'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|9.0'
    appSettings: >
      -KEY_VAULT_URI https://spiritkeys.vault.azure.net/
      -AzureAd__Instance https://externalid14.ciamlogin.com/
      -AzureAd__TenantId c4f79ef7-d330-47c3-ac52-dc268ebf3293
      -AzureAd__ClientId 2e219690-3de6-403e-9a9f-f27610316558
      -AzureAd__CallbackPath /signin-oidc
      -AzureWebJobsStorage__tableServiceUri https://spiritualguide8313.table.core.windows.net
      -ALLOWED_ORIGINS https://zealous-water-0ccf68303.1.azurestaticapps.net

    DeploymentTypeLinux: 'zipDeploy'

